include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    require_trailing_commas: true

analyzer:
  exclude: [lib/**.g.dart, lib/**.freezed.dart]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

formatter:
  page_width: 80
